src/test/java/byteceps/commands/ParserTest.java
=> Add parseInput success test method

src/test/java/byteceps/commands/ParserTest.java
=> Add JUnit test for parseCommand() method

src/main/java/byteceps/commands/ExerciseCommand.java, src/main/java/byteceps/exercises/ExerciseManager.java, src/test/java/byteceps/commands/ExerciseCommandTest.java
Implements #10 
Implements editExercise() in ExerciseCommand class and corresponding editExercise() in ExerciseManager class
Adds corresponding tests in ExerciseCommandTest class
=> Edit an exercise entry to implement

src/main/java/byteceps/ByteCeps.java, src/main/java/byteceps/activities/Workout.java, src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WorkoutManager.java
Implemented the following:
- Create a workout plan
- Add exercise to a workout plan
- Remove exercise from workout plan
- List exercise in a workout plan
=> Implement workout feature

src/main/java/byteceps/processing/WorkoutManager.java, src/test/java/byteceps/activities/ActivityTest.java, src/test/java/byteceps/activities/ExerciseTest.java, src/test/java/byteceps/activities/WorkoutTest.java
Added JUnit Test for 
1. Activity.java
2. Exercise.java
3. Workout.java
Fixed minor bug of adding duplicated exercises to same workout plan
=> Add JUnit Test 

src/main/java/byteceps/ByteCeps.java, src/main/java/byteceps/activities/Workout.java, src/main/java/byteceps/commands/Parser.java, src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WeeklyProgramManager.java, src/main/java/byteceps/processing/WorkoutManager.java
=> Add weeklyProgramManager class

src/main/java/byteceps/processing/WorkoutManager.java, src/test/java/byteceps/processing/WorkoutManagerTest.java
=> Delete workout plan

src/main/java/byteceps/processing/ActivityManager.java, src/main/java/byteceps/processing/WorkoutManager.java, src/test/java/byteceps/processing/WorkoutManagerTest.java
1. Add asserts for Workoutmanager
2. Minor fix for delete method in activity manager where it make sure that entity is deleted in hashmap as well
=> Add asserts for Workoutmanager

src/main/java/byteceps/activities/Workout.java, src/main/java/byteceps/commands/Parser.java, src/main/java/byteceps/processing/ActivityManager.java, src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WeeklyProgramManager.java, src/main/java/byteceps/ui/UserInterface.java, src/test/java/byteceps/processing/ExerciseManagerTest.java
During the rework, most of the code that was contribute was wrongly attributed to me. I have added back authorship comments and also fixed some things along the way
=> Credit authors for methods + Cleanup

src/main/java/byteceps/processing/ActivityManager.java, src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WeeklyProgramManager.java, src/main/java/byteceps/processing/WorkoutManager.java, src/test/java/byteceps/processing/ExerciseManagerTest.java, src/test/java/byteceps/processing/WorkoutManagerTest.java
=> Add week /today function, add assertions

src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WeeklyProgramManager.java, src/main/java/byteceps/processing/WorkoutManager.java
fixes #46, 
also added assertions to WorkoutManager, WeeklyProgramManager and ExerciseManager's execute() classes
=> Fix workout bugs, add more assertions

src/main/java/byteceps/commands/Parser.java, src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WeeklyProgramManager.java, src/main/java/byteceps/processing/WorkoutManager.java, src/test/java/byteceps/commands/ParserTest.java
Fixes #47 (except week /clean)
=> Fix week bugs

src/main/java/byteceps/processing/WeeklyProgramManager.java
=> Clean up code

.gitignore, src/main/java/byteceps/processing/ExerciseManager.java
=> Fix edit bugs

src/main/java/byteceps/activities/Activity.java, src/main/java/byteceps/activities/Day.java, src/main/java/byteceps/processing/ActivityManager.java, src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WeeklyProgramManager.java, src/main/java/byteceps/storage/Storage.java, src/test/java/byteceps/activities/ActivityTest.java, src/test/java/byteceps/activities/ExerciseTest.java, src/test/java/byteceps/activities/WorkoutTest.java
Fixes #61. 
Also, am proposing a new format for the weeklyProgram JSON object alongside the rework.
=> Refactor WeeklyProgramManager and Rework HashMap to HashSet

src/main/java/byteceps/processing/ActivityManager.java, src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WorkoutManager.java, src/test/java/byteceps/processing/ExerciseManagerTest.java, src/test/java/byteceps/processing/WorkoutManagerTest.java
Implemented search functionality for exercises & workout plans
=> Search for exercises & workout plans 

src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WorkoutManager.java
=> Bug fix for list command

src/main/java/byteceps/ByteCeps.java, src/main/java/byteceps/activities/Exercise.java, src/main/java/byteceps/activities/TrackedExercise.java, src/main/java/byteceps/activities/TrackedWorkout.java, src/main/java/byteceps/activities/Workout.java, src/main/java/byteceps/commands/Parser.java, src/main/java/byteceps/processing/ActivityManager.java, src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/TrackedWorkoutsManager.java, src/main/java/byteceps/processing/WeeklyProgramManager.java, src/main/java/byteceps/processing/WorkoutManager.java, src/main/java/byteceps/storage/Storage.java, src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
Implements #54 . 
- changed `week` to `program`
- `program /today` lists all exercises assigned today **and** your tracked exercises if you have tracked them
- `program /history` shows tracked workouts by date
- `program /history <yyyy-mm-dd>` shows the completed/tracked exercises on the given date
- `program /track` requires you to assign a workout to a given day through `program /assign <workoutName> /to <day of week>`
- `program /track <exerciseName> /weight <int> /sets <int> /reps <int>` tracks an exercise for today
- `program /track <exerciseName> /weight <int> /sets <int> /reps <int> /date <yyyy-mm-dd>` tracks an exercise for a given date (requires an assigned workout for that day also)
=> Implement Tracking of Workouts

src/main/java/byteceps/processing/ActivityManager.java
=> SLAP the search method in ActivityManager.

src/main/java/byteceps/storage/Storage.java, src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
=> Handle corrupted json file

src/main/java/byteceps/activities/Activity.java, src/main/java/byteceps/activities/Exercise.java, src/main/java/byteceps/activities/Workout.java, src/main/java/byteceps/processing/ActivityManager.java, src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WorkoutManager.java, src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
Add javadocs for the following java files:
1. Exercise
2. Activity
3. Workout
4. ExerciseManager
5. ActivityManager
6. WorkoutManager
=> Add javadocs

docs/UserGuide.md, src/main/java/byteceps/ByteCeps.java, src/main/java/byteceps/activities/WorkoutLog.java, src/main/java/byteceps/processing/CascadingDeletionProcessor.java, src/main/java/byteceps/processing/WeeklyProgramManager.java
Handles cascading deletions of exercises and workouts by silently removing them from workouts /programs.
=> Add CascadingDeletionProcessor class

docs/UserGuide.md
Add section detailing 'help /FLAG' command to UG
Fixes #93
=> Add Help Menu section to UG

src/main/java/byteceps/processing/WeeklyProgramManager.java, src/main/java/byteceps/ui/strings/DayStrings.java, src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
=> Bug fix for invalid date & future dates

docs/UserGuide.md
=> Add clearer instruction for program logging

docs/UserGuide.md, src/main/java/byteceps/activities/Workout.java, src/main/java/byteceps/processing/WorkoutManager.java, src/main/java/byteceps/ui/strings/ManagerStrings.java
=> Implement edit workout functionality

docs/UserGuide.md, src/main/java/byteceps/processing/WorkoutManager.java
=> Fix workout lowercase error

src/main/java/byteceps/ui/strings/ManagerStrings.java, src/main/java/byteceps/validators/WeeklyProgramValidator.java
=> Add usage message on incomplete commands

docs/UserGuide.md, src/main/java/byteceps/activities/ExerciseLog.java, src/main/java/byteceps/processing/WeeklyProgramManager.java, src/main/java/byteceps/processing/WorkoutLogsManager.java, src/main/java/byteceps/storage/Storage.java, src/main/java/byteceps/ui/strings/ManagerStrings.java, src/main/java/byteceps/validators/WeeklyProgramValidator.java, src/test/java/byteceps/processing/WeeklyProgramManagerTest.java
=> Add logging for different weights & reps

src/main/java/byteceps/processing/WorkoutLogsManager.java, src/main/java/byteceps/storage/Storage.java, src/main/java/byteceps/ui/strings/ManagerStrings.java, src/main/java/byteceps/validators/WeeklyProgramValidator.java
Fixes some bugs to do with multiple logging. Also refactored some methods for better SLAP.
=> Fix bugs and refactor

docs/DeveloperGuide.md, docs/team/v4vern.md, src/main/java/byteceps/processing/ExerciseManager.java, src/main/java/byteceps/processing/WorkoutManager.java, src/main/java/byteceps/ui/UserInterface.java, src/main/java/byteceps/ui/strings/ManagerStrings.java, src/main/java/byteceps/validators/ExerciseValidator.java, src/main/java/byteceps/validators/WorkoutValidator.java, src/test/java/byteceps/commands/ParserTest.java, src/test/java/byteceps/processing/CascadingDeletionProcessorTest.java, src/test/java/byteceps/processing/WeeklyProgramManagerTest.java, src/test/java/byteceps/ui/UserInterfaceTest.java
Increased test coverage to 82%
=> Add test cases, fix bugs & add documentation

src/main/java/byteceps/storage/Storage.java
Check if parsed date is same as given string
=> Fixes the 31 feb bugs

src/main/java/byteceps/processing/HelpMenuManager.java, src/test/java/byteceps/processing/HelpMenuManagerTest.java, src/test/java/byteceps/validators/HelpValidatorTest.java
Add HelpMenuManager and HelpValidator Testing
Add a thrown exception with error message for a command error case for which only a String was previously returned
=> Add HelpMenuManager and HelpValidator Testing
